openapi: 3.0.0
info:
  title: PokeApi
  version: '2.0'
  description: PokéAPI is free and open to use.
  contact:
    name: Paul Hallett
servers:
  - url: 'https://pokeapi.co/api/v2'
paths:
  '/pokemon-species/{name}':
    get:
      summary: Get Pokemon Species
      tags:
        - Poke
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonSpecies'
              examples: {}
      operationId: getPokemonSpecies
      description: A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon species are shared across all varieties of Pokémon within the species.
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
        description: Pokemon name
components:
  schemas:
    PokemonSpecies:
      description: ''
      type: object
      x-examples: {}
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        order:
          type: number
        gender_rate:
          type: number
        capture_rate:
          type: number
        base_happiness:
          type: number
        is_baby:
          type: boolean
        is_legendary:
          type: boolean
        is_mythical:
          type: boolean
        hatch_counter:
          type: number
        has_gender_differences:
          type: boolean
        forms_switchable:
          type: boolean
        growth_rate:
          $ref: '#/components/schemas/NamedApiResource'
        pokedex_numbers:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/PokemonSpeciesDexEntry'
        egg_groups:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/NamedApiResource'
        color:
          $ref: '#/components/schemas/NamedApiResource'
        shape:
          $ref: '#/components/schemas/PokemonSpeciesDexEntry'
        evolves_from_species:
          $ref: '#/components/schemas/PokemonSpeciesDexEntry'
        evolution_chain:
          $ref: '#/components/schemas/APIResource'
        habitat:
          $ref: '#/components/schemas/NamedApiResource'
        generation:
          $ref: '#/components/schemas/NamedApiResource'
        names:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/Name'
        flavor_text_entries:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/FlavorTextEntry'
        form_descriptions:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/Description'
        genera:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/Genus'
        varieties:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              is_default:
                type: boolean
              pokemon:
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  url:
                    type: string
                    minLength: 1
                required:
                  - name
                  - url
            required:
              - is_default
      required:
        - id
        - name
        - order
        - gender_rate
        - capture_rate
        - base_happiness
        - is_baby
        - is_legendary
        - is_mythical
        - hatch_counter
        - has_gender_differences
        - forms_switchable
        - growth_rate
        - pokedex_numbers
        - egg_groups
        - color
        - shape
        - evolves_from_species
        - evolution_chain
        - generation
        - names
        - flavor_text_entries
        - form_descriptions
        - genera
        - varieties
    FlavorTextEntry:
      description: ''
      type: object
      x-examples: {}
      properties:
        flavor_text:
          type: string
          minLength: 1
        language:
          $ref: '#/components/schemas/NamedApiResource'
        version:
          $ref: '#/components/schemas/NamedApiResource'
      required:
        - flavor_text
        - language
        - version
    Version:
      description: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
        url:
          type: string
          minLength: 1
      required:
        - name
        - url
      x-examples:
        example-1:
          name: red
          url: 'https://pokeapi.co/api/v2/version/1/'
    NamedApiResource:
      title: NamedApiResource
      type: object
      properties:
        name:
          type: string
        url:
          type: string
    PokemonSpeciesDexEntry:
      title: PokemonSpeciesDexEntry
      type: object
      properties:
        entry_number:
          type: string
        pokedex:
          $ref: '#/components/schemas/NamedApiResource'
    APIResource:
      title: APIResource
      type: object
      properties:
        url:
          type: string
    Name:
      title: Name
      type: object
      properties:
        name:
          type: string
        language:
          $ref: '#/components/schemas/NamedApiResource'
    Description:
      title: Description
      type: object
      properties:
        description:
          type: string
        language:
          type: string
    Genus:
      title: Genus
      type: object
      properties:
        genus:
          type: string
        language:
          $ref: '#/components/schemas/NamedApiResource'
    PokemonSpeciesVariety:
      title: PokemonSpeciesVariety
      type: object
      properties:
        is_default:
          type: boolean
        pokemon:
          $ref: '#/components/schemas/NamedApiResource'
tags:
  - name: Poke
